In [2]:
import pandas as pd
import numpy as np
import math

In [3]:
tsunami = pd.read_csv('tsunami_dataset.csv')
#tsunami.tail()
res_set = {'Very Doubtful Tsunami': 0, 'Questionable Tsunami': 1,
           'Definite Tsunami': 3, 'Probable Tsunami': 2,
           'Event that only caused a seiche or disturbance in an inland river': -1}

result = [res_set[row['EVENT_VALIDITY']] for index, row in tsunami.iterrows()]
result
tsunami.insert(21,"EVENT_OCCURRED",result,True)
tsunami

,ID,YEAR,MONTH,DAY,HOUR,MINUTE,LATITUDE,LONGITUDE,LOCATION_NAME,COUNTRY,...,EVENT_VALIDITY,EQ_MAGNITUDE,EQ_DEPTH,TS_INTENSITY,DAMAGE_TOTAL_DESCRIPTION,HOUSES_TOTAL_DESCRIPTION,DEATHS_TOTAL_DESCRIPTION,URL,COMMENTS,EVENT_OCCURRED
0,12,-330,NaN,NaN,NaN,NaN,40.000,25.000,"E. SPORADES ISLANDS, AEGEAN ISLANDS",GREECE,...,Very Doubtful Tsunami,7.0,NaN,NaN,NaN,NaN,NaN,https://www.ngdc.noaa.gov/hazel/view/hazards/t...,"330 B.C. Aegean Sea, Sporades Islands, 40 N 25...",0
1,481,1764,2.0,11.0,NaN,NaN,51.450,-2.583,"BRISTOL, ENGLAND",UK,...,Very Doubtful Tsunami,NaN,NaN,NaN,NaN,NaN,NaN,https://www.ngdc.noaa.gov/hazel/view/hazards/t...,"Reference #1894, in full: ""On Saturday the 11t...",0
2,71,859,NaN,NaN,NaN,NaN,36.080,36.250,SAMANDAGI,TURKEY,...,Questionable Tsunami,NaN,NaN,3.0,NaN,NaN,NaN,https://www.ngdc.noaa.gov/hazel/view/hazards/t...,"859 (possibly 861), November. Levantian Sea, N...",1
3,186,1580,1.0,NaN,NaN,NaN,40.000,128.000,YELLOW SEA,NORTH KOREA,...,Very Doubtful Tsunami,NaN,NaN,1.0,NaN,NaN,NaN,https://www.ngdc.noaa.gov/hazel/view/hazards/t...,<P><blockquote><i>Reference #414:</i></blockqu...,0
4,5,-1300,NaN,NaN,NaN,NaN,39.960,26.240,"IONIAN COASTS, TROAD",TURKEY,...,Questionable Tsunami,6.0,NaN,5.0,NaN,NaN,NaN,https://www.ngdc.noaa.gov/hazel/view/hazards/t...,1300 B.C. Ionian and Aegean Seas. References t...,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2254,5753,2020,7.0,22.0,6.0,12.0,55.030,-158.522,"SHUMAGIN ISLANDS, AK",USA,...,Definite Tsunami,7.8,28.0,NaN,NaN,NaN,NaN,https://www.ngdc.noaa.gov/hazel/view/hazards/t...,NaN,3
2255,5750,2020,6.0,18.0,12.0,49.0,-33.294,-177.838,"S OF RAOUL ISLAND, KERMADEC ISLANDS",NEW ZEALAND,...,Definite Tsunami,7.4,10.0,NaN,NaN,NaN,NaN,https://www.ngdc.noaa.gov/hazel/view/hazards/t...,A small tsunami (12 cm) occurred today followi...,3
2256,5752,2013,4.0,22.0,1.0,16.0,18.081,-102.182,MEXICO,MEXICO,...,Probable Tsunami,6.0,30.0,NaN,NaN,NaN,NaN,https://www.ngdc.noaa.gov/hazel/view/hazards/t...,"In the same subduction zone, earthquakes of Ap...",2
2257,5749,1867,6.0,10.0,NaN,NaN,-7.800,110.400,JAVA,INDONESIA,...,Very Doubtful Tsunami,NaN,NaN,NaN,Severe (~>$5 to $24 million),Many (~101 to 1000 houses),Few (~1 to 50 people),https://www.ngdc.noaa.gov/hazel/view/hazards/t...,A seaquake was observed in the backarc. While ...,0
2258,5751,2020,6.0,23.0,15.0,29.0,16.029,-95.901,OFF OF COAST OF OAXACA,MEXICO,...,Definite Tsunami,7.4,26.0,NaN,Extreme (~$25 million or more),NaN,Few (~1 to 50 people),https://www.ngdc.noaa.gov/hazel/view/hazards/t...,NaN,3

In [4]:
tsunami['EVENT_VALIDITY'].unique()

array(['Very Doubtful Tsunami', 'Questionable Tsunami',
       'Definite Tsunami', 'Probable Tsunami',
       'Event that only caused a seiche or disturbance in an inland river'],
      dtype=object)

In [15]:
from sklearn.model_selection import train_test_split
tsunami_1 = tsunami
tsunami_1['EQ_MAGNITUDE'] = tsunami_1['EQ_MAGNITUDE'].fillna(tsunami['EQ_MAGNITUDE'].mean())
tsunami_2 = tsunami
tsunami_2['EQ_MAGNITUDE'] = tsunami_2['EQ_MAGNITUDE'].fillna(tsunami['EQ_MAGNITUDE'].median())
tsunami_1

,ID,YEAR,MONTH,DAY,HOUR,MINUTE,LATITUDE,LONGITUDE,LOCATION_NAME,COUNTRY,...,EVENT_VALIDITY,EQ_MAGNITUDE,EQ_DEPTH,TS_INTENSITY,DAMAGE_TOTAL_DESCRIPTION,HOUSES_TOTAL_DESCRIPTION,DEATHS_TOTAL_DESCRIPTION,URL,COMMENTS,EVENT_OCCURRED
0,12,-330,NaN,NaN,NaN,NaN,40.000,25.000,"E. SPORADES ISLANDS, AEGEAN ISLANDS",GREECE,...,Very Doubtful Tsunami,7.000000,36.298787,NaN,NaN,NaN,NaN,https://www.ngdc.noaa.gov/hazel/view/hazards/t...,"330 B.C. Aegean Sea, Sporades Islands, 40 N 25...",0
1,481,1764,2.0,11.0,NaN,NaN,51.450,-2.583,"BRISTOL, ENGLAND",UK,...,Very Doubtful Tsunami,7.046676,36.298787,NaN,NaN,NaN,NaN,https://www.ngdc.noaa.gov/hazel/view/hazards/t...,"Reference #1894, in full: ""On Saturday the 11t...",0
2,71,859,NaN,NaN,NaN,NaN,36.080,36.250,SAMANDAGI,TURKEY,...,Questionable Tsunami,7.046676,36.298787,3.0,NaN,NaN,NaN,https://www.ngdc.noaa.gov/hazel/view/hazards/t...,"859 (possibly 861), November. Levantian Sea, N...",1
3,186,1580,1.0,NaN,NaN,NaN,40.000,128.000,YELLOW SEA,NORTH KOREA,...,Very Doubtful Tsunami,7.046676,36.298787,1.0,NaN,NaN,NaN,https://www.ngdc.noaa.gov/hazel/view/hazards/t...,<P><blockquote><i>Reference #414:</i></blockqu...,0
4,5,-1300,NaN,NaN,NaN,NaN,39.960,26.240,"IONIAN COASTS, TROAD",TURKEY,...,Questionable Tsunami,6.000000,36.298787,5.0,NaN,NaN,NaN,https://www.ngdc.noaa.gov/hazel/view/hazards/t...,1300 B.C. Ionian and Aegean Seas. References t...,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2254,5753,2020,7.0,22.0,6.0,12.0,55.030,-158.522,"SHUMAGIN ISLANDS, AK",USA,...,Definite Tsunami,7.800000,28.000000,NaN,NaN,NaN,NaN,https://www.ngdc.noaa.gov/hazel/view/hazards/t...,NaN,3
2255,5750,2020,6.0,18.0,12.0,49.0,-33.294,-177.838,"S OF RAOUL ISLAND, KERMADEC ISLANDS",NEW ZEALAND,...,Definite Tsunami,7.400000,10.000000,NaN,NaN,NaN,NaN,https://www.ngdc.noaa.gov/hazel/view/hazards/t...,A small tsunami (12 cm) occurred today followi...,3
2256,5752,2013,4.0,22.0,1.0,16.0,18.081,-102.182,MEXICO,MEXICO,...,Probable Tsunami,6.000000,30.000000,NaN,NaN,NaN,NaN,https://www.ngdc.noaa.gov/hazel/view/hazards/t...,"In the same subduction zone, earthquakes of Ap...",2
2257,5749,1867,6.0,10.0,NaN,NaN,-7.800,110.400,JAVA,INDONESIA,...,Very Doubtful Tsunami,7.046676,36.298787,NaN,Severe (~>$5 to $24 million),Many (~101 to 1000 houses),Few (~1 to 50 people),https://www.ngdc.noaa.gov/hazel/view/hazards/t...,A seaquake was observed in the backarc. While ...,0
2258,5751,2020,6.0,23.0,15.0,29.0,16.029,-95.901,OFF OF COAST OF OAXACA,MEXICO,...,Definite Tsunami,7.400000,26.000000,NaN,Extreme (~$25 million or more),NaN,Few (~1 to 50 people),https://www.ngdc.noaa.gov/hazel/view/hazards/t...,NaN,3

In [6]:
eq_depth_median = tsunami['EQ_DEPTH'].median()
eq_depth_mean = tsunami['EQ_DEPTH'].mean()
eq_depth_mean
eq_depth_median

31.0

In [7]:
tsunami_11= tsunami_12 = tsunami_21 = tsunami_22 = tsunami
tsunami_11['EQ_DEPTH']  = tsunami_1.EQ_DEPTH.fillna(eq_depth_mean)
tsunami_12['EQ_DEPTH']  = tsunami_1.EQ_DEPTH.fillna(eq_depth_median)
tsunami_21['EQ_DEPTH']  = tsunami_2.EQ_DEPTH.fillna(eq_depth_mean)
tsunami_22['EQ_DEPTH']  = tsunami_2.EQ_DEPTH.fillna(eq_depth_median)
X = tsunami_11[['LATITUDE','LONGITUDE','EQ_DEPTH','EQ_MAGNITUDE']]
y = tsunami_11['EVENT_OCCURRED']

In [8]:
from sklearn.ensemble import RandomForestRegressor

X_train, X_val, y_train, y_val = train_test_split(X,y)
y_train

478     0
1852    3
1985    0
898     1
1525    3
       ..
1589    3
871     3
1521    3
515     3
361     2
Name: EVENT_OCCURRED, Length: 1694, dtype: int64

In [9]:
model = RandomForestRegressor(random_state=0, n_estimators = 200)
model.fit(X_train,y_train)

preds = model.predict(X_val)
preds = [math.ceil(x) for x in preds]

In [10]:
from sklearn.metrics import mean_absolute_error

vals = mean_absolute_error(y_val,model.predict(X_val))
vals

0.8034085042581919

In [11]:
z = model.predict([[-33.294,-177.838,7.400000,10.000000]])
math.ceil(z)

c:\Users\Snigdha\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
C:\Users\Snigdha\AppData\Local\Temp\ipykernel_2268\1945821878.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  math.ceil(z)

3

In [12]:
frequency_3 = {}
frequency_2 = {}
frequency_1 = {}
frequency_0 = {}

# Iterate through each row in the DataFrame
for index, row in tsunami.iterrows():
    region = row['REGION']
    event_occurred = row['EVENT_OCCURRED']
    
    if event_occurred == 3:
        if region not in frequency_3:
            frequency_3[region] = 0
        frequency_3[region] += 1
    elif event_occurred == 2:
        if region not in frequency_2:
            frequency_2[region] = 0
        frequency_2[region] += 1
    elif event_occurred == 1:
        if region not in frequency_1:
            frequency_1[region] = 0
        frequency_1[region] += 1
    elif event_occurred == 0:
        if region not in frequency_0:
            frequency_0[region] = 0
        frequency_0[region] += 1

frequency_3

{'Japan': 257,
 'Mediterranean Sea': 80,
 'China, North and South Korea, Philippines, Taiwan': 46,
 'Caribbean Sea': 40,
 'West Coast of South America': 62,
 'Northeast Atlantic Ocean': 27,
 'West Coast of North and Central America': 53,
 'Indonesia (Pacific Ocean) and Malaysia': 33,
 'Kamchatka and Kuril Islands': 62,
 'Indian Ocean (including west coast of Australia)': 47,
 'E Coast Australia, New Zealand, South Pacific Is.': 59,
 'Hawaii, Johnston Atoll, Midway I': 9,
 'Alaska (including Aleutian Islands)': 45,
 'New Caledonia, New Guinea, Solomon Is., Vanuatu': 93,
 'East Coast USA and Canada, St Pierre and Miquelon': 3,
 'Black Sea and Caspian Sea': 9,
 'Red Sea and Persian Gulf': 3,
 'Northwest Atlantic Ocean': 3,
 'Southwest Atlantic Ocean': 1}

In [13]:
avg = (frequency_3['Japan']*3+frequency_2['Japan']*2+frequency_1['Japan']*1)/(frequency_3['Japan']+frequency_2['Japan']+frequency_1['Japan'])

In [14]:
tsunami['CAUSE'].unique()

array(['Earthquake', 'Unknown', 'Volcano', 'Landslide',
       'Volcano and Landslide', 'Earthquake and Landslide',
       'Questionable Earthquake', 'Volcano and Earthquake',
       'Meteorological', 'Explosion', nan], dtype=object)

In [16]:
import pickle
with open('tsunami_model.pkl','wb') as file:
    pickle.dump(model,file)